import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import type { SupabaseClient } from '@supabase/supabase-js'
import { signIn, USER } from './helpers'

/**
 * Acceptance suite B - pro-rating, as a regression against the source
 * spreadsheet.
 *
 * The workbook computed (1 + (31-Dec - hire)) / 365 x 18 and got
 * 10.553424657534247 for a 1 June hire, alongside a hand-written sanity check
 * of 1.5 x 7 = 10.5 in a scratch cell. Both methods are implemented here and
 * both land on 10.5, which is the number HR can actually explain to staff.
 */
describe('B. Pro-rating', () => {
  let db: SupabaseClient
  let admin: SupabaseClient
  let originalMethod: string

  const prorate = async (
    hireDate: string,
    leaveYear: number,
    baseDays: number,
    exitDate: string | null = null,
  ) => {
    const { data, error } = await db.rpc('fn_prorate_entitlement', {
      p_hire_date: hireDate,
      p_leave_year: leaveYear,
      p_base_days: baseDays,
      p_exit_date: exitDate,
    })
    if (error) throw error
    return Number(data)
  }

  const setMethod = async (method: 'monthly_accrual' | 'daily_365') => {
    const { error } = await admin
      .from('app_settings')
      .update({ prorate_method: method })
      .eq('id', 1)
    if (error) throw error
  }

  beforeAll(async () => {
    db = await signIn(USER.chantha)
    admin = await signIn(USER.sophea) // system_admin - only they may change settings
    const { data } = await admin.from('app_settings').select('prorate_method').eq('id', 1).single()
    originalMethod = data!.prorate_method
  })

  afterAll(async () => {
    await setMethod(originalMethod as 'monthly_accrual' | 'daily_365')
  })

  it('B1. hire 2026-06-01, year 2026, base 18, monthly_accrual -> 10.5', async () => {
    await setMethod('monthly_accrual')
    expect(await prorate('2026-06-01', 2026, 18)).toBe(10.5)
  })

  it('B2. hire 2026-06-01, year 2026, base 18, daily_365 -> 10.5 (10.553 rounded)', async () => {
    await setMethod('daily_365')
    expect(await prorate('2026-06-01', 2026, 18)).toBe(10.5)
  })

  it('B3. hire 2024-03-15, year 2026, base 18 -> 18.0 (prior-year hires are not pro-rated)', async () => {
    await setMethod('monthly_accrual')
    expect(await prorate('2024-03-15', 2026, 18)).toBe(18)
    // ...and the same under the other method, because no pro-rating happens at all.
    await setMethod('daily_365')
    expect(await prorate('2024-03-15', 2026, 18)).toBe(18)
  })

  it('B4. hire 2020-01-01, exit 2026-06-30, year 2026, base 18, monthly_accrual -> 9.0', async () => {
    await setMethod('monthly_accrual')
    expect(await prorate('2020-01-01', 2026, 18, '2026-06-30')).toBe(9)
  })

  it('B5. hire 2026-12-20, year 2026, base 18 -> 0.0 (no completed month)', async () => {
    await setMethod('monthly_accrual')
    expect(await prorate('2026-12-20', 2026, 18)).toBe(0)
  })

  it('B6. hire after the leave year ends -> 0.0', async () => {
    await setMethod('monthly_accrual')
    expect(await prorate('2027-03-01', 2026, 18)).toBe(0)
  })

  it('B7. exit before the leave year starts -> 0.0', async () => {
    await setMethod('monthly_accrual')
    expect(await prorate('2020-01-01', 2026, 18, '2025-11-30')).toBe(0)
  })

  it('B8. both methods land on a whole half day, never a float', async () => {
    for (const method of ['monthly_accrual', 'daily_365'] as const) {
      await setMethod(method)
      for (let month = 1; month <= 12; month++) {
        const hire = `2026-${String(month).padStart(2, '0')}-01`
        const result = await prorate(hire, 2026, 18)
        expect(result * 2).toBe(Math.round(result * 2))
      }
    }
  })

  it('B9. the seeded 1-June-2026 joiner really does hold 10.5 annual days', async () => {
    // Sreymom Kim, hired 2026-06-01. This is the end-to-end version of B1:
    // the entitlement row generated by fn_generate_entitlements, not the
    // function called in isolation.
    await setMethod('monthly_accrual')
    const { error: genError } = await admin.rpc('fn_generate_entitlements', {
      p_leave_year: 2026,
      p_employee_id: '88888888-8888-4888-8888-888888888888',
    })
    if (genError) throw genError

    const { data, error } = await admin
      .from('entitlements')
      .select('prorated_days')
      .eq('employee_id', '88888888-8888-4888-8888-888888888888')
      .eq('leave_type_code', 'ANNUAL')
      .eq('leave_year', 2026)
      .single()
    if (error) throw error
    expect(Number(data.prorated_days)).toBe(10.5)
  })
})
